spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: path-planning-service
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/path_planning?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# 服务器配置
server:

uav:
  jwt:
    secret: dThpc3RhbmRvbmx5Zm9ydGVzdGluZzM2MmJ5dGVzbG9uZ3NlY3JldGtleQ==