server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - io.github.resilience4j.bulkhead.autoconfigure.BulkheadAutoConfiguration
      - io.github.resilience4j.timelimiter.autoconfigure.TimeLimiterAutoConfiguration
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

uav:
  jwt:
    secret: dThpc3RhbmRvbmx5Zm9ydGVzdGluZzM2MmJ5dGVzbG9uZ3NlY3JldGtleQ==
