spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ground-station-weather-service
  autoconfigure:
    exclude:
      - io.github.resilience4j.bulkhead.autoconfigure.BulkheadAutoConfiguration
      - io.github.resilience4j.timelimiter.autoconfigure.TimeLimiterAutoConfiguration

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/uav_ground_station_weather?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import: classpath:health-config.yml

# 服务器配置
server:
  port: 8088
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
