input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [fields][service] {
    mutate {
      add_tag => ["docker-logs"]
    }
  }
  if [json] {
    json {
      source => "json"
      target => "parsed"
    }
  }
  mutate {
    remove_field => ["ecs", "agent", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "uav-logs-%{+YYYY.MM.dd}"
    action => "index"
  }
  stdout { codec => rubydebug }
}
