import os

base = r'd:\Developer\workplace\py\iteam\trae\data-assimilation-platform'

# Define all replacements per file. Each entry: (file_path, list_of_(old, new))
files_fixes = {
    'algorithm_core/docker/README.md': [
        ('系?Docker', '系统 Docker'),
        ('本文?', '本文档'),
        ('快速开?', '快速开始'),
        ('所有服?', '所有服务'),
        ('# ?REST API', '# 仅 REST API'),
        ('# ?Web 界面', '# 仅 Web 界面'),
        ('变量?|', '变量名|'),
        ('默认?|', '默认值|'),
        ('服务状?', '服务状态'),
        ('默认?root', '默认以 root'),
        ('情况调?', '情况调整'),
        ('Nginx?', 'Nginx'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'benchmarks/README.md': [
        ('性能?', '性能'),
        ('本文?', '本文档'),
        ('基准测?', '基准测试'),
        ('吞吐?|', '吞吐量|'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'algorithm_core/examples/TESTING.md': [
        ('测试指?', '测试指南'),
        ('线中?', '线中'),
        ('在?`algorithm_core', '在 `algorithm_core'),
        ('日志输出?', '日志输出'),
        ('## 依赖?', '## 依赖项'),
        ('**必要依赖**?', '**必要依赖**'),
        ('**可选依赖*?', '**可选依赖**'),
        ('测试报?', '测试报告'),
        ('基线?|', '基线值|'),
        ('≥?100万点/?', '≥100万点/秒'),
        ('≤?1GB', '≤1GB'),
        ('使用限?', '使用限制'),
        ('网格插值时?', '网格插值时间'),
        ('最大时?', '最大时间'),
        ('≤?1?', '≤1秒'),
        ('自动运行?', '自动运行'),
        ('拉取请?', '拉取请求'),
        ('中使用?', '中使用'),
        ('发送通知?', '发送通知'),
        ('Slack通知?', 'Slack通知'),
        ('邮件通知?', '邮件通知'),
        ('SMTP用户?', 'SMTP用户名'),
        ('邮?', '邮箱'),
        ('基线要?', '基线要求'),
        ('性能指标?', '性能指标'),
        ('处理数据?', '处理数据量'),
        ('MB?', 'MB'),
        ('检查失?*', '检查失败**'),
        ('硬件资?', '硬件资源'),
        ('测试数据?', '测试数据量'),
        ('在?`test_performance', '在 `test_performance'),
        ('在?`check_performance', '在 `check_performance'),
        ('?00万点/?', '100万点/秒'),
        # time-related ? at end of sentences
        ('的时?\n', '的时间\n'),
        ('时间1?\n', '时间1秒\n'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'algorithm_core/docs/CHANGELOG.md': [
        ('文件中?', '文件中'),
        ('CN/1.0.0/)?', 'CN/1.0.0/)'),
        ('lang/zh-CN/)?', 'lang/zh-CN/)'),
        ('同化算?\n', '同化算法\n'),
        ('滤波算?\n', '滤波算法\n'),
        ('种算法?', '种算法'),
        ('Block Parallel?', 'Block Parallel'),
        ('分布式计?\n', '分布式计算\n'),
        ('适配器模?\n', '适配器模块\n'),
        ('数据适配?\n', '数据适配器\n'),
        ('观测数据适配?\n', '观测数据适配器\n'),
        ('网格数据适配?\n', '网格数据适配器\n'),
        ('数据验证?\n', '数据验证\n'),
        ('异常检?\n', '异常检测\n'),
        ('风险评估?\n', '风险评估\n'),
        ('热力图生?\n', '热力图生成\n'),
        ('可视化模?\n', '可视化模块\n'),
        ('静态图?\n', '静态图表\n'),
        ('仪表?\n', '仪表盘\n'),
        ('命令行接?\n', '命令行接口\n'),
        ('APIFastAPI?', 'API (FastAPI)'),
        ('面Flask?', '面 (Flask)'),
        ('工作流管?\n', '工作流管理\n'),
        ('处理工作?\n', '处理工作流\n'),
        ('数据源模?\n', '数据源模块\n'),
        ('卫星数据?\n', '卫星数据源\n'),
        ('雷达数据?\n', '雷达数据源\n'),
        ('GPU 加速支?\n', 'GPU 加速支持\n'),
        ('CUDA 加?\n', 'CUDA 加速\n'),
        ('JAX 加?\n', 'JAX 加速\n'),
        ('容器化部?\n', '容器化部署\n'),
        ('多环境支?\n', '多环境支持\n'),
        ('不匹配问?\n', '不匹配问题\n'),
        ('deprecated ?API', 'deprecated 的 API'),
        ('项目初始?\n', '项目初始化\n'),
        ('文档初始?\n', '文档初始化\n'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'algorithm_core/examples/结果分析.md': [
        ('背景场左图?*', '背景场（左图）**'),
        ('预报风?', '预报风场'),
        ('周期性波?*', '周期性波**'),
        ('正?余弦函数', '正弦/余弦函数'),
        ('m/s?', 'm/s'),
        ('网格?*', '网格**'),
        ('?1213', ' × 1213'),
        ('?3.2', '：3.2'),
        ('分析场中图?*', '分析场（中图）**'),
        ('修正风?', '修正风场'),
        ('区域 ?3.2', '区域：3.2'),
        ('价?*', '价值**'),
        ('方差场右图?*', '方差场（右图）**'),
        ('不确定性分?*', '不确定性分布**'),
        ('红?高', '红色=高'),
        ('不确定?', '不确定'),
        ('方差?.25', '方差2.25'),
        ('?量', '。量'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'algorithm_core/README.md': [
        ('README.md)?', 'README.md)'),
        ('功能特?', '功能特点'),
        ('卡尔曼滤?\n', '卡尔曼滤波\n'),
        ('地面站?', '地面站'),
        ('数据重采?', '数据重采样'),
        ('数据验?', '数据验证'),
        ('异常检?', '异常检测'),
        ('分布式计?\n', '分布式计算\n'),
        ('### 可视?', '### 可视化'),
        ('结果可视?', '结果可视化'),
        ('风险热力?', '风险热力图'),
        ('不确定性分?', '不确定性分布'),
        ('GPU支持?', 'GPU支持'),
        ('快速开?', '快速开始'),
        ('配置文件?', '配置文件'),
        ('## 开?', '## 开发'),
        ('开发依?', '开发依赖'),
        ('## API 参?', '## API 参考'),
        ('### 核心?', '### 核心类'),
        ('同化器?|', '同化器|'),
        ('卡尔曼滤?|', '卡尔曼滤波|'),
        ('混合同化?|', '混合同化|'),
        ('### 并行管理?', '### 并行管理器'),
        ('Dask 分布?|', 'Dask 分布式|'),
        ('Ray 分布?|', 'Ray 分布式|'),
        ('## 许可?', '## 许可证'),
        ('根目?[LICENSE]', '根目录 [LICENSE]'),
        # tree structure
        ('?   bayesian_assimilation/', '    bayesian_assimilation/'),
        ('?       core/', '        core/'),
        ('?       models/', '        models/'),
        ('?       parallel/', '        parallel/'),
        ('?       api/', '        api/'),
        ('?       adapters/', '        adapters/'),
        ('?       visualization/', '        visualization/'),
        ('?       quality_control/', '        quality_control/'),
        ('?       risk_assessment/', '        risk_assessment/'),
        ('?       workflows/', '        workflows/'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'README.md': [
        ('平台?UAV', '平台是 UAV'),
        ('数据支?3D-VAR?D-VAREnKF', '数据支持 3D-VAR、4D-VAR、EnKF'),
        ('微服?', '微服务'),
        ('自动化脚?', '自动化脚本'),
        ('本文?', '本文档'),
        ('快速开?', '快速开始'),
        ('配置数据?', '配置数据库'),
        ('MySQL ?Redis', 'MySQL 和 Redis'),
        ('创建数据?', '创建数据库'),
        ('或运?JAR', '或运行 JAR'),
        ('支持的算?', '支持的算法'),
        ('卡尔曼滤?|', '卡尔曼滤波|'),
        ('不确定性量?|', '不确定性量化|'),
        ('执行贝叶斯同?', '执行贝叶斯同化'),
        ('计算方差?', '计算方差'),
        ('健康检?', '健康检查'),
        ('所有测?', '所有测试'),
        ('覆盖?|', '覆盖率|'),
        ('测试?|', '测试数|'),
        ('开发环?', '开发环境'),
        ('所有服?', '所有服务'),
        ('性能基准测试?', '性能基准测试'),
        ('基准测?', '基准测试'),
        ('吞吐?|', '吞吐量|'),
        ('CPU 使用?|', 'CPU 使用率|'),
        ('数据库安?', '数据库安全'),
        ('?useSSL=true', '?useSSL=true'),  # already correct, but there might be issues
        # wait, let me re-check
        ('核心算法库文?|', '核心算法库文档|'),
        ('开发指?', '开发指南'),
        ('# 格式?', '# 格式化'),
        ('# 检?', '# 检查'),
        ('# 类型检?', '# 类型检查'),
        ('# 格式?', '# 格式化'),
        ('新功?', '新功能'),
        ('开发流?', '开发流程'),
        ('推送分?*', '推送分支**'),
        ('所?PR', '所有 PR'),
        ('代码审?', '代码审查'),
        ('许可?', '许可证'),
        ('许可证?', '许可证'),
        ('算法参?*', '算法参考**'),
        # tree
        ('?   src/', '    src/'),
        ('?  ?   bayesian_assimilation/', '        bayesian_assimilation/'),
        ('?  ?   data/', '        data/'),
        ('?  ?   models/', '        models/'),
        ('?  ?   utils/', '        utils/'),
        ('?   tests/', '    tests/'),
        ('?   benchmarks/', '    benchmarks/'),
        ('?   requirements.txt', '    requirements.txt'),
        ('?   setup.py', '    setup.py'),
        ('?', ''),
        ('    src/', '    src/'),
        ('        java/', '        java/'),
        ('        resources/', '        resources/'),
        ('    test/', '    test/'),
        ('    pom.xml', '    pom.xml'),
        ('    application.yml', '    application.yml'),
        ('    api/', '    api/'),
        ('    models/', '    models/'),
        ('    utils/', '    utils/'),
        ('    proto/', '    proto/'),
        ('    config/', '    config/'),
        ('    README.md', '    README.md'),
        ('    kubernetes/', '    kubernetes/'),
        ('    docker/', '    docker/'),
        ('    docker-compose.yml', '    docker-compose.yml'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/index.md': [
        ('平台文?', '平台文档'),
        ('使用教?|', '使用教程|'),
        ('集成方?|', '集成方法|'),
        ('功能包括?', '功能包括：'),
        ('多算法同?*', '多算法同化**'),
        ('支?3D-VAR?D-VAREnKF', '支持 3D-VAR、4D-VAR、EnKF'),
        ('混合同化算?', '混合同化算法'),
        ('数据融?', '数据融合'),
        ('并行框?', '并行框架'),
        ('硬件加?*', '硬件加速**'),
        ('支?CPUGPU', '支持 CPU、GPU'),
        ('JAX 加?', 'JAX 加速'),
        ('可视?*', '可视化**'),
        ('快速链?', '快速链接'),
        ('项目?README', '项目 README'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/development.md': [
        ('开发指?', '开发指南'),
        ('编辑模式?', '编辑模式'),
        ('数据?', '数据源'),
        ('可视?', '可视化'),
        ('工作?', '工作流'),
        ('格式?*使?Black', '格式化**：使用 Black'),
        ('使?isortprofile=black', '使用 isort，profile=black'),
        ('类型检查*使?mypy', '类型检查**：使用 mypy'),
        ('使?flake8', '使用 flake8'),
        ('格式化代?', '格式化代码'),
        ('检查代?', '检查代码'),
        ('覆盖率报?', '覆盖率报告'),
        ('Git 工作?', 'Git 工作流'),
        ('提交代码遵?Conventional', '提交代码遵循 Conventional'),
        ('新功?', '新功能'),
        ('构建与发?', '构建与发布'),
        ('构建?', '构建包'),
        ('发布?PyPI', '发布到 PyPI'),
        ('调试技?', '调试技巧'),
        ('确保?`algorithm_core', '确保在 `algorithm_core'),
        ('回退?CPU', '回退到 CPU'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/uav_integration.md': [
        ('系统集?', '系统集成'),
        ('安全性?', '安全性'),
        # ASCII diagram - these ? are part of the diagram boxes, probably corner characters
        ('路径规划系?', '路径规划系统'),
        ('同化平?', '同化平台'),
        ('同化核?', '同化核心'),
        ('方差?', '方差）'),
        ('提供?REST', '提供 REST'),
        ('高性能?', '高性能'),
        ('批处理?', '批处理'),
        ('观测站数?|', '观测站数据|'),
        ('分析?|', '分析场|'),
        ('不确定性估?|', '不确定性估计|'),
        ('逐小时更?|', '逐小时更新|'),
        ('# ?Java', '# 与 Java'),
        ('监控与日?', '监控与日志'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/tutorials.md': [
        ('安装与配?', '安装与配置'),
        ('安装算法?', '安装算法库'),
        ('准备背景?', '准备背景场'),
        ('分析场形?', '分析场形状'),
        ('方差场形?', '方差场形状'),
        ('可视化结?', '可视化结果'),
        ('完整工作流示?', '完整工作流示例'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/api.md': [
        ('API 参?', 'API 参考'),
        ('同化计算?', '同化计算'),
        ('请求?*?', '请求体'),
        ('响应**?', '响应体'),
        ('健康检?', '健康检查'),
        ('# 可视?', '# 可视化'),
        ('### 核心?', '### 核心类'),
        ('### 模型?', '### 模型类'),
        ('## 错误?', '## 错误码'),
        ('内部错?|', '内部错误|'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'docs/architecture.md': [
        # This file appears clean already, but check
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'deployments/README.md': [
        ('部署方式?', '部署方式'),
        ('本文?', '本文档'),
        ('开发环?', '开发环境'),
        ('用?|', '用途|'),
        ('配置?|', '配置数据|'),
        ('数据库密?|', '数据库密码|'),
        ('可选变?', '可选变量'),
        ('默认?|', '默认值|'),
        ('## ?安全配置', '## 安全配置'),
        # tree
        ('?   Dockerfile', '    Dockerfile'),
        ('?   Dockerfile.dev', '    Dockerfile.dev'),
        ('?   nginx.conf', '    nginx.conf'),
        ('?   deployment.yaml', '    deployment.yaml'),
        ('?   service.yaml', '    service.yaml'),
        ('?   configmap.yaml', '    configmap.yaml'),
        ('?   secrets.yaml', '    secrets.yaml'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    '.github/PULL_REQUEST_TEMPLATE.md': [
        # Only BOM issue
    ],
    'shared/protos/README.md': [
        ('向后兼容?', '向后兼容'),
        ('版本兼?', '版本兼容'),
        ('v1 ?v2', 'v1 和 v2'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'shared/README.md': [
        ('模块包?Protocol', '模块包含 Protocol'),
        ('本文?', '本文档'),
        ('Protos 子模?', 'Protos 子模块'),
        ('核心算法?|', '核心算法|'),
        ('快速开?', '快速开始'),
        ('版本号规?*:', '版本号规则**:'),
        ('添加新字?', '添加新字段'),
        ('不兼容更?', '不兼容更改'),
        ('不兼容更?*', '不兼容更改**'),
        ('重命名字?', '重命名字段'),
        ('示例消?', '示例消息'),
        ('许可?', '许可证'),
        ('许可证?', '许可证'),
        # tree
        ('?   common/', '    common/'),
        ('?  ?   common.proto', '        common.proto'),
        ('?  ?   types.proto', '        types.proto'),
        ('?  ?   README.md', '        README.md'),
        ('?   assimilation/', '    assimilation/'),
        ('?  ?   request.proto', '        request.proto'),
        ('?  ?   response.proto', '        response.proto'),
        ('?   README.md', '    README.md'),
        ('?', ''),
        ('        assimilation/', '        assimilation/'),
        ('        validation/', '        validation/'),
        ('        common/', '        common/'),
        # Fix broken tree - already handled above
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'service_spring/README.md': [
        ('功能?REST', '功能的 REST'),
        ('本文?', '本文档'),
        ('快速开?', '快速开始'),
        ('开发模?', '开发模式'),
        ('REST 控制?', 'REST 控制器'),
        ('查询状?|', '查询状态|'),
        ('健康检?|', '健康检查|'),
        ('所有测?', '所有测试'),
        ('特定测试?', '特定测试类'),
        ('覆盖率报?', '覆盖率报告'),
        # tree
        ('?   main/', '    main/'),
        ('?  ?   java/com/uav/assimilation/', '        java/com/uav/assimilation/'),
        ('?  ?  ?   controller/', '            controller/'),
        ('?  ?  ?   service/', '            service/'),
        ('?  ?  ?   repository/', '            repository/'),
        ('?  ?  ?   model/', '            model/'),
        ('?  ?  ?   config/', '            config/'),
        ('?  ?  ?   dto/', '            dto/'),
        ('?  ?   resources/', '        resources/'),
        ('?  ?       application.yml', '            application.yml'),
        ('?  ?       application-dev.yml', '            application-dev.yml'),
        ('?  ?       application-prod.yml', '            application-prod.yml'),
        ('?  ?       application-test.yml', '            application-test.yml'),
        ('?   test/', '    test/'),
        ('?       java/', '        java/'),
        ('?       resources/', '        resources/'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'scripts/README.md': [
        ('工具脚本?', '工具脚本'),
        ('环境部?|', '环境部署|'),
        ('所有测?|', '所有测试|'),
        ('数据库备?|', '数据库备份|'),
        ('环境部?', '环境部署'),
        ('所有测?', '所有测试'),
        ('### 数据?', '### 数据处理'),
        ('备份数据?', '备份数据库'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'shared/protos/common/README.md': [
        ('所?Protocol', '所有 Protocol'),
        ('位置等?|', '位置等|'),
        ('元数据定?|', '元数据定义|'),
        ('数据结?|', '数据结构|'),
        ('向后兼?', '向后兼容'),
        ('类?', '类型'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
    'service_python/README.md': [
        ('独?API', '独立的 API'),
        ('接口?', '接口'),
        ('本文?', '本文档'),
        ('快速开?', '快速开始'),
        ('健康检?|', '健康检查|'),
        # tree
        ('?   routes/', '    routes/'),
        ('?   schemas/', '    schemas/'),
        ('?   main.py', '    main.py'),
        ('**最后更新*:', '**最后更新**:'),
        ('**维护者*:', '**维护者**:'),
    ],
}

count = 0
for rel_path, replacements in files_fixes.items():
    file_path = os.path.join(base, rel_path)
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            count += 1
    
    if content != original:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'FIXED: {rel_path} ({len([r for r in replacements if r[0] in original])} replacements)')
    else:
        print(f'NO CHANGES: {rel_path}')

print(f'\nTotal replacements: {count}')
