/**
 * KML 工具：航线导出为标准 KML 格式
 * 兼容 PX4 / ArduPilot 等主流飞控
 * 使用方法：
 *   import { exportToKML, buildKML } from '@/utils/kml'
 *   exportToKML(waypoints, 'mission')   // 直接下载
 *   const xml = buildKML(waypoints)    // 获字符串
 */

/**
 * 将航点数组转换为 KML 字符串
 * @param {Array<{lat: number, lng: number, alt?: number, name?: string, description?: string}>} waypoints
 * @param {string} missionName - 任务名称
 * @param {object} options
 * @param {string} options.lineColor - 航线颜色（abgr 格式，如 'ff00ff00'）
 * @param {number} options.lineWidth - 航线宽度
 * @param {string} options.altitudeMode - 高度模式（absolute/relativeToGround/clampToGround）
 * @returns {string} KML XML 字符串
 */
export function buildKML(waypoints, missionName = 'UAV Mission', options = {}) {
  const {
    lineColor = 'ff0066ff',   // 蓝色（ABGR）
    lineWidth = 4,
    altitudeMode = 'absolute'
  } = options

  if (!waypoints || waypoints.length === 0) {
    return buildEmptyKML(missionName)
  }

  const placemarks = waypoints.map((wp, i) => {
    const name = wp.name || `WP${i}`
    const desc = wp.description || `Point ${i + 1}`
    const alt = wp.alt ?? 50
    return `    <Placemark>
      <name>${escapeXml(name)}</name>
      <description>${escapeXml(desc)}</description>
      <Point>
        <coordinates>${wp.lng.toFixed(7)},${wp.lat.toFixed(7)},${alt}</coordinates>
      </Point>
    </Placemark>`
  }).join('\n')

  const coords = waypoints.map(wp => {
    const alt = wp.alt ?? 50
    return `${wp.lng.toFixed(7)},${wp.lat.toFixed(7)},${alt}`
  }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2"
     xmlns:gx="http://www.google.com/kml/ext/2.2">
  <Document>
    <name>${escapeXml(missionName)}</name>
    <description>Generated by UAV Path Planning System</description>
    <Style id="routeStyle">
      <LineStyle>
        <color>${lineColor}</color>
        <width>${lineWidth}</width>
      </LineStyle>
    </Style>
    <Placemark>
      <name>${escapeXml(missionName)} - Route</name>
      <styleUrl>#routeStyle</styleUrl>
      <LineString>
        <altitudeMode>${altitudeMode}</altitudeMode>
        <coordinates>${coords}</coordinates>
      </LineString>
    </Placemark>
${placemarks}
  </Document>
</kml>`
}

/**
 * 生成空的 KML（无航点时）
 */
function buildEmptyKML(name) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(name)}</name>
    <description>No waypoints available</description>
  </Document>
</kml>`
}

/**
 * 将航点数组导出为多机 KML（每个无人机一条航线）
 * @param {Array<{id: string, name: string, color: string, waypoints: Array}>} drones
 * @param {string} missionName
 */
export function buildMultiDroneKML(drones, missionName = 'Multi-Drone Mission') {
  const dronePlacemarks = drones.map(drone => {
    const wpPlacemarks = drone.waypoints.map((wp, i) => {
      const alt = wp.alt ?? 50
      return `      <Placemark>
        <name>${escapeXml(drone.name)} WP${i}</name>
        <Point>
          <coordinates>${wp.lng.toFixed(7)},${wp.lat.toFixed(7)},${alt}</coordinates>
        </Point>
      </Placemark>`
    }).join('\n')

    const coords = drone.waypoints.map(wp => {
      const alt = wp.alt ?? 50
      return `${wp.lng.toFixed(7)},${wp.lat.toFixed(7)},${alt}`
    }).join('\n')

    const abgr = hexToABGR(drone.color || '#409EFF')

    return `    <Folder>
      <name>${escapeXml(drone.name)}</name>
      <Placemark>
        <name>${escapeXml(drone.name)} Route</name>
        <LineString>
          <altitudeMode>absolute</altitudeMode>
          <coordinates>${coords}</coordinates>
        </LineString>
        <Style>
          <LineStyle>
            <color>${abgr}</color>
            <width>3</width>
          </LineStyle>
        </Style>
      </Placemark>
${wpPlacemarks}
    </Folder>`
  }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(missionName)}</name>
    <description>Generated by UAV Path Planning System - Multi-Drone</description>
${dronePlacemarks}
  </Document>
</kml>`
}

/**
 * 触发浏览器下载 KML 文件
 * @param {Array} waypoints
 * @param {string} filename - 不含扩展名
 * @param {object} options
 */
export function exportToKML(waypoints, filename = 'uav-mission', options = {}) {
  const kmlString = buildKML(waypoints, filename, options)
  const blob = new Blob([kmlString], { type: 'application/vnd.google-earth.kml+xml;charset=utf-8' })
  downloadBlob(blob, `${filename}.kml`)
}

/**
 * 导出多机航线 KML
 * @param {Array} drones
 * @param {string} filename
 */
export function exportMultiDroneKML(drones, filename = 'multi-drone-mission') {
  const kmlString = buildMultiDroneKML(drones, filename)
  const blob = new Blob([kmlString], { type: 'application/vnd.google-earth.kml+xml;charset=utf-8' })
  downloadBlob(blob, `${filename}.kml`)
}

// ===== 内部工具 =====

/** 触发 Blob 下载 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 5000)
}

/** XML 特殊字符转义 */
function escapeXml(str) {
  if (!str) return ''
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * Hex 颜色转 KML ABGR 格式
 * 例如：#409EFF → ffEFF409
 */
function hexToABGR(hex) {
  const clean = hex.replace('#', '')
  if (clean.length !== 6) return 'ff0066ff'
  const r = clean.slice(0, 2)
  const g = clean.slice(2, 4)
  const b = clean.slice(4, 6)
  return `ff${b}${g}${r}`   // AABBGGRR
}
